# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8757513d3fa7e477b0ca3d866c4db960a7f005dc93ff394690e7f23f6ebc3d220d46de10e35aeaca882b17cd7f616715101e5b365cac74490d4e3c53a17822b0

test:
  secret_key_base: 1a4804ce71a947b90eeb24a8c8069beff93a9398209046bd5d19c6ab01f554e21d806b46ec6e11f7992d41f5bbde36911c9699d801075245ad31638081aa543b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
