# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed7a7aba7f87b5423fdecd7def7db7a553599469b7b6642a16fa933e402ee388b2c086d4c277ca3fd33593cd218fac07b2b497aa153203ebdb97b2c2336bb57e

test:
  secret_key_base: e2056581a75d640f888d88c800f7698788c3d655a943b4b7041214ff3dfe72000fb54fba21868b1f5947e25210d34de2464dcedccc71b2c8286baca6bc7d6f1f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
