# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3ee39443693de96521c3f7997509fb5ef8ae330c3cf3fb749ea38e52bde1751fe20f275b35d82a1e9b3c30c919a8c291b92083db42b08afbbb1b4fdaf33329e

test:
  secret_key_base: 1906bf2214b74e30dcb370c44258f38752d0c5ce70f32f525f0c503bea1144dc1073509f9872cff710677fe8d24979301f0a6f20bf1fd3bbd24e4961cf0f11f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
